branch-defaults:
  default:
    environment: yaap-dev
environment-defaults:
  yaap-dev:
    branch: null
    repository: null
global:
  application_name: yaap
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-central-1::platform/Node.js running
    on 64bit Amazon Linux/4.0.1
  default_region: eu-central-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
